apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  namespace: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
      - name: voting
        image: docker/example-voting-app-vote
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.1"
            memory: "64Mi"
          limits:
            cpu: "0.3"
            memory: "128Mi"
